2 spaces > 4 spaces lol

diff --git a/hue/hue b/hue/hue
--- a/hue/hue
+++ b/hue/hue
@@ -3,7 +3,7 @@
 source $HOME/.huerc
 
 usage() {
-    cat <<EOF
+  cat <<EOF
 Usage: `basename $0` [-h host] [-u username] command [options]
 
 Commands:
@@ -16,91 +16,91 @@ Commands:
 
     run [script]
 EOF
-    exit 1
+  exit 1
 }
 
 die() {
-    local msg="$1"
-    echo $msg >&2
-    exit 1
+  local msg="$1"
+  echo $msg >&2
+  exit 1
 }
 
 api_url() {
-    local suffix="$1"
-    printf 'http://%s/api/%s/%s' $HOST $USERNAME $suffix
+  local suffix="$1"
+  printf 'http://%s/api/%s/%s' $HOST $USERNAME $suffix
 }
 
 get_status() {
-    local light="$1"
-    local suffix='lights'
-    [[ -n "$light" ]] && suffix="${suffix}/${light}"
-    curl --silent `api_url $suffix` | jq .
+  local light="$1"
+  local suffix='lights'
+  [[ -n "$light" ]] && suffix="${suffix}/${light}"
+  curl --silent `api_url $suffix` | jq .
 }
 
 get_power() {
-    local light="$1"
-    local url="$(api_url lights/$light)"
-    curl --silent $url | jq .state.on
+  local light="$1"
+  local url="$(api_url lights/$light)"
+  curl --silent $url | jq .state.on
 }
 
 set_power() {
-    local light="$1"
-    local state="$2"
-    local url="$(api_url lights/$light/state)"
+  local light="$1"
+  local state="$2"
+  local url="$(api_url lights/$light/state)"
 
-    case $state in
-        on)
-            data='{"on": true}'
-            ;;
-        off)
-            data='{"on": false}'
-            ;;
-        *)
-            die "Invalid state $state"
-            ;;
-    esac
+  case $state in
+    on)
+      data='{"on": true}'
+      ;;
+    off)
+      data='{"on": false}'
+      ;;
+    *)
+      die "Invalid state $state"
+      ;;
+  esac
 
-    curl --silent -XPUT -d "$data" $url
+  curl --silent -XPUT -d "$data" $url
 }
 
 get_scene() {
-    local light="$1"
-    get_status "$light" | jq .state.bri
+  local light="$1"
+  get_status "$light" | jq .state.bri
 }
 
 set_scene() {
-    local light="$1"
-    local bri="${2:-254}"
-    local url="$(api_url lights/$light/state)"
+  local light="$1"
+  local bri="${2:-254}"
+  local url="$(api_url lights/$light/state)"
 
-    local data="{\"on\": true, \"bri\": $bri}"
-    curl --silent -XPUT -d "$data" $url
+  local data="{\"on\": true, \"bri\": $bri}"
+  curl --silent -XPUT -d "$data" $url
 }
 
 run_script() {
-    local script="$1"
+  local script="$1"
 
-    local realpath=$(dirname $(readlink $0))
-    local script_dir=$realpath/scripts
-    local script_file=$script_dir/${script}.hue
-    [[ -e "$script_file" ]] || die "Script $script doesn't exist"
+  local realpath=$(dirname $(readlink $0))
+  local script_dir=$realpath/scripts
+  local script_file=$script_dir/${script}.hue
+  [[ -e "$script_file" ]] || die "Script $script doesn't exist"
 
-    local runhue=$realpath/runhue
-    $runhue < $script_file
+  local runhue=$realpath/runhue
+  $runhue < $script_file
 }
 
 while getopts 'u:h:' opt; do
-    case $opt in
-        u)
-            USERNAME=$OPTARG
-            ;;
-        h)
-            HOST=$OPTARG
-            ;;
-        *)
-            usage
-            ;;
-    esac
+  case $opt in
+    u)
+      USERNAME=$OPTARG
+      ;;
+    h)
+      HOST=$OPTARG
+      ;;
+    *)
+      usage
+      ;;
+  esac
 done
 
 shift $((OPTIND - 1))
@@ -108,38 +108,38 @@ shift $((OPTIND - 1))
 command="${1:-status}"
 shift
 case $command in
-    status)
-        get_status $1
-        ;;
-    power)
-        light="$1"
-        state="$2"
-        [[ -n "$light" ]] || die 'Missing required light parameter'
-        if [ -z "$state" ]; then
-            get_power $light
-        else
-            set_power $light $state
-        fi
-        ;;
-    scene)
-        light="$1"
-        bri="$2"
-        [[ -n "$light" ]] || die 'Missing required light parameter'
-        if [ -z "$bri" ]; then
-            get_scene $light
-        else
-            set_scene $light $bri
-        fi
-        ;;
-    run)
-        script="$1"
-        [[ -n "$script" ]] || die 'Missing script parameter'
+  status)
+    get_status $1
+    ;;
+  power)
+    light="$1"
+    state="$2"
+    [[ -n "$light" ]] || die 'Missing required light parameter'
+    if [ -z "$state" ]; then
+      get_power $light
+    else
+      set_power $light $state
+    fi
+    ;;
+  scene)
+    light="$1"
+    bri="$2"
+    [[ -n "$light" ]] || die 'Missing required light parameter'
+    if [ -z "$bri" ]; then
+      get_scene $light
+    else
+      set_scene $light $bri
+    fi
+    ;;
+  run)
+    script="$1"
+    [[ -n "$script" ]] || die 'Missing script parameter'
 
-        run_script $script
-        ;;
-    *)
-        usage
-        ;;
+    run_script $script
+    ;;
+  *)
+    usage
+    ;;
 esac
 
 exit $?
